import { useEffect, useState } from 'react';
import Icon from '../components/Icon.jsx';
import { getActivityLog } from '../services/api.js';
function dt(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)}
function label(v){return String(v||'ACTIVITY').replaceAll('_',' ')}
export default function ActivityLogPage({selectedDivision='ALL',searchTerm=''}){
 const [items,setItems]=useState([]),[pagination,setPagination]=useState({page:1,total:0,totalPages:1}),[actions,setActions]=useState([]),[action,setAction]=useState(''),[user,setUser]=useState(''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>setPage(1),[selectedDivision,searchTerm,action,user,dateFrom,dateTo]);
 async function load(){setLoading(true);setError('');try{const r=await getActivityLog({divisionId:selectedDivision,query:searchTerm,user,action,dateFrom,dateTo,page,pageSize:50});setItems(r.data?.items||[]);setPagination(r.data?.pagination||{page:1,total:0,totalPages:1});setActions(r.data?.actions||[])}catch(e){setError(e.message||'Activity Log gagal dimuat.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[selectedDivision,searchTerm,action,user,dateFrom,dateTo,page]);
 return <main className="workspace-content activity-workspace"><div className="workspace-heading doc-heading"><div><h1>Activity Log</h1><p>Audit trail aktivitas KASA Digital Archive.</p></div><div className="doc-heading-metrics"><span><strong>{Number(pagination.total||0).toLocaleString('id-ID')}</strong> Aktivitas</span></div></div>
 <section className="activity-filters"><label><span>User</span><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Username"/></label><label><span>Action</span><select value={action} onChange={e=>setAction(e.target.value)}><option value="">Semua Action</option>{actions.map(x=><option value={x} key={x}>{label(x)}</option>)}</select></label><label><span>Dari</span><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label><span>Sampai</span><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><button onClick={load}>Refresh</button></section>
 {error?<div className="dashboard-error">{error}<button onClick={load}>Coba lagi</button></div>:null}
 <section className="activity-table-card"><div className="activity-table-head"><span>Waktu</span><span>User / Divisi</span><span>Action</span><span>Object</span><span>Detail</span></div>{loading?Array.from({length:8}).map((_,i)=><div className="activity-table-row is-skeleton" key={i}/>):items.map(row=><div className="activity-table-row" key={row.id}><span>{dt(row.occurredAt)}</span><span><strong>{row.username}</strong><small>{row.divisionName||'GLOBAL'}</small></span><span><b>{label(row.action)}</b></span><span><strong>{row.objectName||row.objectType||'—'}</strong><small>{row.objectType||''}</small></span><span>{row.detail||'—'}</span></div>)}</section>
 {!loading&&items.length===0?<div className="fm-empty"><Icon name="activity" size={34}/><strong>Belum ada activity yang cocok</strong><span>Ubah filter atau pencarian.</span></div>:null}
 <div className="ops-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Sebelumnya</button><span>Halaman {pagination.page||1} / {pagination.totalPages||1}</span><button disabled={page>=Number(pagination.totalPages||1)} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div>
 </main>
}
