import { useEffect, useMemo, useState } from 'react';
import Icon from '../components/Icon.jsx';
import { getRecycleBin, permanentlyDeleteRecycleDocument, permanentlyDeleteRecycleFolder, restoreRecycleDocument, restoreRecycleFolder } from '../services/api.js';

function formatDate(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function formatBytes(bytes){const n=Number(bytes||0);if(!n)return'0 B';if(n<1024)return`${n} B`;if(n<1024**2)return`${(n/1024).toFixed(1)} KB`;if(n<1024**3)return`${(n/1024**2).toFixed(1)} MB`;return`${(n/1024**3).toFixed(2)} GB`}
export default function RecycleBinPage({selectedDivision='ALL'}){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[confirm,setConfirm]=useState(null);
 async function load(){setLoading(true);setError('');try{const r=await getRecycleBin(selectedDivision);setItems(r.data||[])}catch(e){setError(e.message||'Recycle Bin gagal dimuat.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[selectedDivision]);
 const counts=useMemo(()=>({folders:items.filter(x=>x.kind==='folder').length,docs:items.filter(x=>x.kind==='document').length}),[items]);
 async function act(item,type){setBusy(`${item.kind}:${item.data.id}`);setError('');try{if(type==='restore'){item.kind==='document'?await restoreRecycleDocument(item.data.id):await restoreRecycleFolder(item.data.id)}else{item.kind==='document'?await permanentlyDeleteRecycleDocument(item.data.id):await permanentlyDeleteRecycleFolder(item.data.id)}setConfirm(null);await load()}catch(e){setError(e.message||'Aksi Recycle Bin gagal.')}finally{setBusy('')}}
 return <main className="workspace-content recycle-workspace"><div className="workspace-heading doc-heading"><div><h1>Recycle Bin</h1><p>Restore item atau pindahkan file/folder Google Drive ke Trash secara permanen dari aplikasi.</p></div><div className="doc-heading-metrics"><span><strong>{counts.folders}</strong> Folder</span><span><strong>{counts.docs}</strong> Dokumen</span></div></div>
 <div className="ops-warning"><Icon name="trash" size={16}/><span><strong>Hapus Permanen</strong> akan menandai metadata sebagai PURGED dan memindahkan item fisik ke Trash Google Drive.</span></div>
 {error?<div className="dashboard-error">{error}<button onClick={load}>Coba lagi</button></div>:null}
 {loading?<div className="recycle-list">{Array.from({length:6}).map((_,i)=><div className="activity-item skeleton-activity" key={i}/>)}</div>:items.length===0?<div className="fm-empty"><Icon name="trash" size={34}/><strong>Recycle Bin kosong</strong><span>Item yang dihapus dari File Manager akan muncul di sini.</span></div>:<div className="recycle-list">{items.map(item=>{const row=item.data,key=`${item.kind}:${row.id}`,isBusy=busy===key;return <article className="recycle-row" key={key}><div className="recycle-kind"><Icon name={item.kind==='folder'?'folder':'document'} size={19}/></div><div className="recycle-copy"><strong>{item.kind==='folder'?row.name:(row.documentName||row.originalFilename)}</strong><span>{row.divisionName||'—'} · {item.kind==='document'?formatBytes(row.fileSize):'Folder'} · Dihapus {formatDate(item.deletedAt)} {item.deletedBy?`oleh ${item.deletedBy}`:''}</span></div><div className="recycle-actions"><button disabled={isBusy} onClick={()=>act(item,'restore')}><Icon name="history" size={14}/> Restore</button><button className="danger" disabled={isBusy} onClick={()=>setConfirm(item)}><Icon name="trash" size={14}/> Hapus Permanen</button></div></article>})}</div>}
 {confirm?<div className="folder-modal-backdrop"><article className="folder-modal"><div className="folder-modal-head"><div><span>PERMANENT DELETE</span><h2>Hapus Permanen?</h2></div><button onClick={()=>setConfirm(null)}><Icon name="close" size={18}/></button></div><div className="folder-modal-body"><p className="folder-confirm-copy"><strong>{confirm.kind==='folder'?confirm.data.name:confirm.data.originalFilename}</strong> akan berstatus PURGED dan item Google Drive dipindahkan ke Trash. Aksi ini tidak dapat direstore melalui aplikasi.</p></div><div className="folder-modal-footer"><button className="secondary" onClick={()=>setConfirm(null)}>Batal</button><button className="danger-btn" onClick={()=>act(confirm,'purge')}>Hapus Permanen</button></div></article></div>:null}
 </main>
}
